name: cryosiam
channels:
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  - python=3.10
  - numpy=1.24.4
  - pandas=2.0.3
  - scipy=1.9.1
  - h5py=3.11.0
  - scikit-learn=1.3.2
  - pytorch-cuda=11.8
  - pytorch=2.1.2
  - torchvision=0.16.2
  - itk=5.3.0
  - pyyaml=6.0.2
  - plotly=5.24.1
  - python-elf=0.5.2
  - lightning==2.1.3
  - monai==1.3.2
  - mrcfile==1.5.3
  - scikit-image=0.20.0
  - pip
  - pip:
      - edt==2.4.1
      - umap-learn==0.5.7