data_folder: '/g/zaugg/stojanov/simulated_datasets/final_models/dense_simsiam_regression/version_6/predictions/'
labels_folder: '/g/mahamid/stojanov/simulated_datasets/simulated_data/tomograms/semantic'
log_dir: '/g/zaugg/stojanov/simulated_datasets/final_models/dense_simsiam_semantic_binary/complexes/rubisco/'
file_extension: '.mrc'

selected_labels: [ 18 ]
filtered_labels_folder: '/g/mahamid/stojanov/simulated_datasets/simulated_data/tomograms/semantic_rubisco'

train_files: ['sample_1.mrc', 'sample_2.mrc', 'sample_3.mrc', 'sample_4.mrc', 'sample_5.mrc', 
              'sample_6.mrc', 'sample_7.mrc', 'sample_8.mrc', 'sample_9.mrc', 'sample_10.mrc', 
              'sample_11.mrc', 'sample_12.mrc', 'sample_13.mrc', 'sample_14.mrc', 'sample_15.mrc', 
              'sample_16.mrc', 'sample_17.mrc', 'sample_18.mrc', 'sample_19.mrc', 'sample_20.mrc', 
              'sample_21.mrc', 'sample_22.mrc', 'sample_23.mrc', 'sample_24.mrc', 'sample_25.mrc', 
              'sample_26.mrc', 'sample_27.mrc', 'sample_28.mrc', 'sample_29.mrc', 'sample_30.mrc', 
              'sample_31.mrc', 'sample_32.mrc', 'sample_33.mrc', 'sample_34.mrc', 'sample_35.mrc', 
              'sample_36.mrc', 'sample_37.mrc', 'sample_38.mrc', 'sample_39.mrc', 'sample_40.mrc', 
              'sample_41.mrc', 'sample_42.mrc', 'sample_43.mrc', 'sample_44.mrc', 'sample_45.mrc', 
              'sample_46.mrc', 'sample_47.mrc', 'sample_48.mrc', 'sample_49.mrc', 'sample_50.mrc', 
              'sample_51.mrc', 'sample_52.mrc', 'sample_53.mrc', 'sample_54.mrc', 'sample_55.mrc', 
              'sample_56.mrc', 'sample_57.mrc', 'sample_58.mrc', 'sample_59.mrc', 'sample_60.mrc', 
              'sample_61.mrc', 'sample_62.mrc', 'sample_63.mrc', 'sample_64.mrc', 'sample_65.mrc', 
              'sample_66.mrc', 'sample_67.mrc', 'sample_68.mrc', 'sample_69.mrc', 'sample_70.mrc', 
              'sample_71.mrc', 'sample_72.mrc', 'sample_73.mrc', 'sample_74.mrc', 'sample_75.mrc', 
              'sample_76.mrc', 'sample_77.mrc', 'sample_78.mrc', 'sample_79.mrc', 'sample_80.mrc', 
              'sample_81.mrc', 'sample_82.mrc', 'sample_83.mrc', 'sample_84.mrc', 'sample_85.mrc', 
              'sample_86.mrc', 'sample_87.mrc', 'sample_88.mrc', 'sample_89.mrc', 'sample_90.mrc', 
              'sample_91.mrc', 'sample_92.mrc', 'sample_93.mrc', 'sample_94.mrc', 'sample_95.mrc', 
              'sample_96.mrc', 'sample_97.mrc', 'sample_98.mrc', 'sample_99.mrc', 'sample_100.mrc', 
              'sample_101.mrc', 'sample_102.mrc', 'sample_103.mrc', 'sample_104.mrc', 'sample_105.mrc', 
              'sample_106.mrc', 'sample_107.mrc', 'sample_108.mrc', 'sample_109.mrc', 'sample_110.mrc', 
              'sample_111.mrc', 'sample_112.mrc', 'sample_113.mrc', 'sample_114.mrc', 'sample_115.mrc', 
              'sample_116.mrc', 'sample_117.mrc', 'sample_118.mrc', 'sample_119.mrc', 'sample_120.mrc', 
              'sample_121.mrc', 'sample_122.mrc', 'sample_123.mrc', 'sample_124.mrc', 'sample_125.mrc', 
              'sample_126.mrc', 'sample_127.mrc', 'sample_128.mrc', 'sample_129.mrc', 'sample_130.mrc', 
              'sample_131.mrc', 'sample_132.mrc', 'sample_133.mrc', 'sample_134.mrc', 'sample_135.mrc', 
              'sample_136.mrc', 'sample_137.mrc', 'sample_138.mrc', 'sample_139.mrc', 'sample_140.mrc', 
              'sample_141.mrc', 'sample_142.mrc', 'sample_143.mrc', 'sample_144.mrc', 'sample_145.mrc', 
              'sample_146.mrc', 'sample_147.mrc', 'sample_148.mrc', 'sample_149.mrc', 'sample_150.mrc', 
              'sample_151.mrc', 'sample_152.mrc', 'sample_153.mrc', 'sample_154.mrc', 'sample_155.mrc', 
              'sample_156.mrc', 'sample_157.mrc', 'sample_158.mrc', 'sample_159.mrc', 'sample_160.mrc', 
              'sample_161.mrc', 'sample_162.mrc', 'sample_163.mrc', 'sample_164.mrc', 'sample_165.mrc', 
              'sample_166.mrc', 'sample_167.mrc', 'sample_168.mrc', 'sample_169.mrc', 'sample_170.mrc', 
              'sample_171.mrc', 'sample_172.mrc', 'sample_173.mrc', 'sample_174.mrc', 'sample_175.mrc', 
              'sample_176.mrc', 'sample_177.mrc', 'sample_178.mrc', 'sample_179.mrc', 'sample_180.mrc', 
              'sample_181.mrc', 'sample_182.mrc', 'sample_183.mrc', 'sample_184.mrc', 'sample_185.mrc', 
              'sample_186.mrc', 'sample_187.mrc', 'sample_188.mrc', 'sample_189.mrc', 'sample_190.mrc', 
              'sample_191.mrc', 'sample_192.mrc', 'sample_193.mrc', 'sample_194.mrc', 'sample_195.mrc', 
              'sample_196.mrc', 'sample_197.mrc', 'sample_198.mrc', 'sample_199.mrc', 'sample_200.mrc' ]

test_files: ['sample_201.mrc', 'sample_202.mrc', 'sample_203.mrc', 'sample_204.mrc', 'sample_205.mrc', 
             'sample_206.mrc', 'sample_207.mrc', 'sample_208.mrc', 'sample_209.mrc', 'sample_210.mrc', 
             'sample_211.mrc', 'sample_212.mrc', 'sample_213.mrc', 'sample_214.mrc', 'sample_215.mrc', 
             'sample_216.mrc', 'sample_217.mrc', 'sample_218.mrc', 'sample_219.mrc', 'sample_220.mrc', 
             'sample_221.mrc', 'sample_222.mrc', 'sample_223.mrc', 'sample_224.mrc', 'sample_225.mrc', 
             'sample_226.mrc', 'sample_227.mrc', 'sample_228.mrc', 'sample_229.mrc', 'sample_230.mrc', 
             'sample_231.mrc', 'sample_232.mrc', 'sample_233.mrc', 'sample_234.mrc', 'sample_235.mrc', 
             'sample_236.mrc', 'sample_237.mrc', 'sample_238.mrc', 'sample_239.mrc', 'sample_240.mrc', 
             'sample_241.mrc', 'sample_242.mrc', 'sample_243.mrc', 'sample_244.mrc', 'sample_245.mrc', 
             'sample_246.mrc', 'sample_247.mrc', 'sample_248.mrc', 'sample_249.mrc', 'sample_250.mrc', 
             'sample_251.mrc', 'sample_252.mrc', 'sample_253.mrc', 'sample_254.mrc', 'sample_255.mrc', 
             'sample_256.mrc', 'sample_257.mrc', 'sample_258.mrc', 'sample_259.mrc', 'sample_260.mrc', 
             'sample_261.mrc', 'sample_262.mrc', 'sample_263.mrc', 'sample_264.mrc', 'sample_265.mrc', 
             'sample_266.mrc', 'sample_267.mrc', 'sample_268.mrc', 'sample_269.mrc', 'sample_270.mrc', 
             'sample_271.mrc', 'sample_272.mrc', 'sample_273.mrc', 'sample_274.mrc', 'sample_275.mrc', 
             'sample_276.mrc', 'sample_277.mrc', 'sample_278.mrc', 'sample_279.mrc', 'sample_280.mrc', 
             'sample_281.mrc', 'sample_282.mrc', 'sample_283.mrc', 'sample_284.mrc', 'sample_285.mrc', 
             'sample_286.mrc', 'sample_287.mrc', 'sample_288.mrc', 'sample_289.mrc', 'sample_290.mrc', 
             'sample_291.mrc', 'sample_292.mrc', 'sample_293.mrc', 'sample_294.mrc', 'sample_295.mrc', 
             'sample_296.mrc', 'sample_297.mrc', 'sample_298.mrc', 'sample_299.mrc']
