data_folder: '/scratch/stojanov/mycoplasma_data/vpp/240422/'
instances_mask_folder: '/scratch/stojanov/mycoplasma_data/vpp/240422/instances'
log_dir: '/scratch/stojanov/development/cryoet-torch/experiments/simsiam'
prediction_folder: '/scratch/stojanov/development/cryoet-torch/experiments/simsiam/predictions'
trained_model: '/g/zaugg/stojanov/simulated_datasets/experiments/simsiam/version_0/model/last.ckpt'
contrastive: True
file_extension: '.mrc'

test_files: null
clustering_files: null
visualization_files: null

min_particle_size: 10
max_particle_size: null
masking_type: 1
expand_labels: 2

clustering_kmeans:
  num_clusters: 10
  visualization: True

clustering_spectral:
  num_clusters: 10
  estimate_num_clusters: False
  visualization: True

# Visualization parameters
visualization:
  prediction_folder: '/g/zaugg/stojanov/simulated_datasets/experiments/cryosiam_dna_filaments/predictions/simsiam_1_4/kmeans'
  pca_components: null
  visualization_suffix: 'instance_regions_clusters.csv'
  visualize_umap: True
  3d_umap: False
  visualize_3d_mask: True
  3d_mask_extension: '.mrc' # either .mrc or .h5

parameters:
  gpu_devices: 0
  data:
    patch_size: [ 64, 64, 64 ]
    patch_overlap: null
    min: 0
    max: 1
    mean: 0
    std: 1
  network:
    spatial_dims: 3
    in_channels: 1
    dim: 1024

hyper_parameters:
  batch_size: 10