name: Conda Build & Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  conda-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true

      - name: Install conda-build
        run: |
          conda install -y conda-build

      - name: Build Conda package
        run: |
          conda build conda-recipe/

      - name: Test import
        run: |
          source activate base
          python -c "import cryosiam"