data_folder: '/g/mahamid/stojanov/simulated_datasets/simulated_data/tomograms/noisy_ctf_corrected_min_z_200_inverted_scaled/'
gt_folder: '/g/mahamid/stojanov/simulated_datasets/simulated_data/tomograms/without_noise_min_z_200_inverted_scaled/'
patches_folder: '/scratch/stojanov/simulated_datasets/experiments/dense_simsiam_regression/patches_0'
log_dir: '/g/zaugg/stojanov/simulated_datasets/final_models/dense_simsiam_regression'
prediction_folder: '/g/zaugg/stojanov/simulated_datasets/final_models/dense_simsiam_regression/predictions'
pretrained_model: '/g/zaugg/stojanov/simulated_datasets/experiments/dense_simsiam/version_1/model/last.ckpt'
file_extension: '.mrc'

train_files: ['sample_1.mrc', 'sample_2.mrc', 'sample_3.mrc', 'sample_4.mrc', 'sample_5.mrc',
              'sample_6.mrc', 'sample_7.mrc', 'sample_8.mrc', 'sample_9.mrc', 'sample_10.mrc']

val_files: null
validation_ratio: 0.1

continue_training: False

parameters:
  nodes: 1
  gpu_devices: 8
  data:
    patch_size: [ 128, 128, 128 ]
    remove_empty_patches: False
    patch_overlap: 0.5
    min: 0
    max: 1
    mean: 0
    std:  1
  transforms:
    low_pass_sigma_range: null
    high_pass_sigma_range: null
    high_pass_sigma2_range: null
    noise_sigma_range: null
    combine_transforms: False
    scale_intensity_factors: null
  network:
    in_channels: 1
    spatial_dims: 3
    n_output_channels: 1
    dense_dim: 64
    filters: [ 32, 64 ]
    kernel_size: 3
    padding: 1
    unfreeze_decoder: True
    unfreeze_backbone: True
    loss_type: 'combined'

hyper_parameters:
  cache_rate: 0
  val_interval: 1
  batch_size: 3
  optimizer: 'adamw' # one of 'sgd', 'adam', 'adamw'
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.00001
  max_epochs: 200
